/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.Circulo;
import entidades.Cuadrado;
import entidades.Rectangulo;
import entidades.Triangulo;
import java.awt.event.ItemEvent;
import utilidades.Utilidades;

/**
 *
 * @author jbuitrago
 */
public class FigurasFrame extends javax.swing.JFrame {

    /**
     * Creates new form FigurasFrame
     */
    public FigurasFrame() {
        initComponents();
        label1.setText("Lado");
        label2.setText("");
        label1.setVisible(true);
        label2.setVisible(false);
        
        text1.setText("");
        text2.setText("");
        text1.setVisible(true);
        text2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboFigura = new javax.swing.JComboBox<>();
        label2 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();
        areaButton = new javax.swing.JButton();
        perimetroButton = new javax.swing.JButton();
        respuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboFigura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cuadrado", "Rectangulo", "Circulo", "Triangulo" }));
        comboFigura.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboFiguraItemStateChanged(evt);
            }
        });

        label2.setText("Lado");

        label1.setText("jLabel1");

        areaButton.setText("Area");
        areaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaButtonActionPerformed(evt);
            }
        });

        perimetroButton.setText("Perimetro");
        perimetroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perimetroButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(areaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(perimetroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(areaButton)
                    .addComponent(perimetroButton)
                    .addComponent(respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaButtonActionPerformed

        int parametro1 = Utilidades.obtenerParametro(text1.getText());
        int parametro2 = Utilidades.obtenerParametro(text2.getText());

        switch (comboFigura.getSelectedIndex()) {
            case 0:
                Cuadrado cuadrado = new Cuadrado(parametro1);
                respuesta.setText(Integer.toString(cuadrado.area()));
                break;
            case 1:
                Rectangulo rectangulo = new Rectangulo(parametro1, parametro2);
                respuesta.setText(Integer.toString(rectangulo.area()));
                break;
            case 2:
                Circulo circulo = new Circulo(parametro1);
                respuesta.setText(Integer.toString(circulo.area()));
                break;
            case 3:
                Triangulo triangulo = new Triangulo(parametro1, parametro2);
                respuesta.setText(Integer.toString(triangulo.area()));
                break;
        }
    }//GEN-LAST:event_areaButtonActionPerformed

    private void perimetroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perimetroButtonActionPerformed
        int parametro1 = Utilidades.obtenerParametro(text1.getText());
        int parametro2 = Utilidades.obtenerParametro(text2.getText());

        switch (comboFigura.getSelectedIndex()) {
            case 0:
                Cuadrado cuadrado = new Cuadrado(parametro1);
                respuesta.setText(Integer.toString(cuadrado.perimetro()));
                break;
            case 1:
                Rectangulo rectangulo = new Rectangulo(parametro1, parametro2);
                respuesta.setText(Integer.toString(rectangulo.perimetro()));
                break;
            case 2:
                Circulo circulo = new Circulo(parametro1);
                respuesta.setText(Integer.toString(circulo.perimetro()));
                break;
            case 3:
                Triangulo triangulo = new Triangulo(parametro1, parametro2);
                respuesta.setText(Integer.toString(triangulo.perimetro()));
                break;
        }
    }//GEN-LAST:event_perimetroButtonActionPerformed

    private void comboFiguraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboFiguraItemStateChanged
         int indice = comboFigura.getSelectedIndex();
        switch (indice) {
            case 0:
                label1.setText("Lado"); 
                label2.setText(""); 
                label1.setVisible(true);
                label2.setVisible(false);
                
                text1.setText("");
                text2.setText("");
                text1.setVisible(true);
                text2.setVisible(false);
                break;
            case 1:
                label1.setText("Lado 1"); 
                label2.setText("Lado 2"); 
                label1.setVisible(true);
                label2.setVisible(true);
                
                text1.setText("");
                text2.setText("");
                text1.setVisible(true);
                text2.setVisible(true);
                break;
            case 2:
                label1.setText("Perimetro"); 
                label2.setText(""); 
                label1.setVisible(true);
                label2.setVisible(false);
                
                text1.setText("");
                text2.setText("");
                text1.setVisible(true);
                text2.setVisible(false);
                break;
            case 3:
                label1.setText("Base"); 
                label2.setText("Altura"); 
                label1.setVisible(true);
                label2.setVisible(true);
                
                text1.setText("");
                text2.setText("");
                text1.setVisible(true);
                text2.setVisible(true);
                break;
        }
    }//GEN-LAST:event_comboFiguraItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FigurasFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FigurasFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton areaButton;
    private javax.swing.JComboBox<String> comboFigura;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton perimetroButton;
    private javax.swing.JTextField respuesta;
    private javax.swing.JTextField text1;
    private javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
